sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 8.0
services: docker
before_install:
    - cd RestWithASPNETUdemy/
    - echo "CI bem sucessedido!"
script:
    - docker-compose build
before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
    provider: script
    script:
        docker tag rest-with-aspnet-db:latest $DOCKER_USERNAME/rest-with-aspnet-db:$TRAVIS_JOB_ID;
        docker tag rest-with-aspnet:latest $DOCKER_USERNAME/rest-with-aspnet:$TRAVIS_JOB_ID;
        docker push $DOCKER_USERNAME/rest-with-aspnet:$TRAVIS_JOB_ID;
        docker push $DOCKER_USERNAME/rest-with-aspnet-db:$TRAVIS_JOB_ID;
    on:
        branch: main
notifications:
    email: false
